language: node_js
node_js: '8'
deploy:
  provider: npm
  email: dbalaban@lampix.co
  api_key:
    secure: jLiT6PO/sQ8ny6j/ekpAM1s6KOnR+ZdAnyD8daZ1ukJqN/LDmsl1F23NSinxm8+iLZie6b8LI1IU1ij5tU9bv+NZhb6cIOEbbXBkdhguEbCit+bdsBNgcAeuGJik29ZjO+sEEYiNT113d7miqY7DbLKFaezaFuXx4GoorLFPmWs4Y3DUqZhRZ0J93FHrci1aoefbPeF/NQp3D8T16AILQRSmw9ewGUJeSX/73xar0qBShDKlVucgC/VNYWmGqfNlvkLIEpMbArvSZC2zCXHaGCb3fKtW4/VakcZfhp5wo/wePII4+UCv2eZymZgBzrMDVAKr3YxNq5S0So4rSDKknDJZoceW9iawBmZZ3NZMTlH30GHHipUwHp/K8YL0DmC+XLuoghDYs8q2Rs75rUOOnM1BbdiEs+0TlwjjM+kgVC6Jpxp0whfGp+VZfBC6Pg80RwVbVG1aU40HW3BbqvqF353rmdqjnZr1FgPmMQnxlD42Yu1XNkcQCWWBTBgR5h6sy3ftb14KiLPgYSgw2rOqGn6VJEFjMKeLkuXze1xkkHIGDteG8p03QmkDf/980a3KtAXf0Tiz03yqZeH4jrjamdcDDPgsFMx9fxydTNA0nw4wiy1YsQjLtvlJ8dHpYQy/y1z1mZUepxW8jwlECvKmzXRJJLK5/1e8Dv0eT4kmJLo=
  skip_cleanup: true
  on:
    repo: lampix-org/lampixjs-physics
    all_branches: true
branches:
  only:
  - "/^release\\/\\d+\\.\\d+\\.\\d+$/"
