language: node_js
node_js: '8'
deploy:
  provider: npm
  email: dbalaban@lampix.co
  api_key:
    secure: RymlFgyn2HIONikzQG6Mlt2ieTIabVEmHZdWnuRnARGyaQOi8bQGxjIz6yLwd99A6i7i9TTLsPvpA8sQZhDgE1n4cuZYVJGQmMJyyAK9BEdzefS33jkW67Xf9isbyquzK+XEzPjvuGlYFoLfrk48kW8rsnjstKgaLlTVFf8HhJVPrYt38y/lASBj4+ZzFJwCCYJJQmVkeASWiZ9di0qt6MQa5oZsaCGZSxtneNzymM87Un6JGmiw1Y0pWRTIdExMWKsnV/mxsTw3SiaJyCITN8BXJRyqNx+a+dFk52Ld1fwHVx65fodMsg7aoNwoDhOsFHpoY9HDkdpcOEdBWpZsoq0TDKHap1tIRGjHPfcZaBfk0GkzaVZPJtzwLkZf8+0ij6BYrnioVd3JzO+WdzeS8RS2GiNz4EQdlSQXOimZnnT8eXViBmqjsXjT5INFotEdGFiXHVXdbC79bfv1QcQyu2BGrCQDYqz8D8LJvjCNvMICvPFYcIqbrLcZbytOgVq1BgbawpFBfbN4n2PpYolaw59NE6nOgRJCuU5p5I9V+H7HAKVbmo5Fr4eMCcXd2kC2rfNcO7N/8k4o/JoqCpyZKGhYdBZUBxfOQwGbm2StKOIXEwcOvX0ry1jGt50YKqRbUH/5so0Zd3DUTSAqJ6ILxdsSkt8BfZuzPd61mhZA1x4=
  skip_cleanup: true
  on:
    repo: lampix-org/lampixjs-physics
    all_branches: true
branches:
  only:
  - "/^release\\/\\d+\\.\\d+\\.\\d+$/"
