language: node_js
node_js: '8'
deploy:
  provider: npm
  email: dbalaban@lampix.co
  api_key:
    secure: r11n5fvMhlOiBCOMSUf5PluJ3Lyvi5RiPSx5TSd8tgblVQ/I0Qxf4YaYnj/6bZiWZ7VQSQ+NaWEI5OedLPfEuVcd7iCiZr79NNFPHsfBCO3428VANLrxTENf8pThZUGYVlZRscqvGDrUlc7AxzsZdzMj4TUQsw+RNG34+JMKzOqUtHbA5wVlp2DcYK/3tUXur6XdYDb6d6/ifvBvwqmyr8xxrx+EGF/03V/Q7DZYmU4uj7GCRq/fp2Qczh93RJAQv6cH3YWjQ2VzF76jVYtLe0GW+++wUjsp+zO6Tv/OBTEvfNP0ew+wmMaCjmFpEA4kyjus5jIwjZoCJ+e8yyZEuwF7VR6pOMFei3qQQ93deXIRjE9Hju+MR2ZebJIy7i1U8U+IPE3SYdFwNwv9CwtGKULoXn/kt9r5R75pbgQGe515nA7zdvxmB5FGyR6ACEyZRjLqbBkCXNVydG43QAQLNlsXzaoeJRRDQBDvnKQqk46pzW08IsBsLZ1qcwYlR/KWuPgTt0LeAjKTQguFySY/Y4n9Tf408HDEYmu5w6gHMYqGa/BjhBZwIqW+7LoEfYPJhmZdnYE+OK3HftxitT2irX0bc6frHP1AkODlwkDZpICqc3u+vN3F7LrjVFquprpE2ZEOQvAAd4hVk554oDLDCDDtxcQCRS/4KLRNPf2Fk6o=
  skip_cleanup: true
  on:
    repo: lampix-org/lampixjs-physics
    all_branches: true
branches:
  only:
  - "/^release\\/\\d+\\.\\d+\\.\\d+$/"
