language: node_js
node_js: '8'
deploy:
  provider: npm
  email: dbalaban@lampix.co
  api_key:
    secure: tRR72EUzJDZIZAz4AqOugmotIStszb/EY7+W8GMeYr6jLpEl1Wmfzolm6Daj2pk7idHsCvo4q5sw8PJ98Ta+dRQ9Ck2tgPD7/9AF4RvW4W4nHVsJYhIKvdjRhycGoV9VkkLNfp+7Ot0ObhFeFsI4t4vpATHImBv/5nsy1lk+9uMW4SELhrGyiZ5Ptw9PPyBnql3yyW3M6nKJ4KC2KmKwo/DLIt6d9twLN3SrBtvjWRI6IfH7n6bbvy/dF5RZ5E5wxHHW7PEy1UDEEbuAr+LuFuAyqSEogZ3zq2Hh4e2OcLYutrgOiG2QcDjaqFnBe42TzOTlGnFJRhfDR+OhRVaxw2IWxvCMSObO3duBnWE53QRlch5gzP6xwc+Fg3c1/VnVQUh7uH5GfpTbcB1JREZ4SM0uC7PEuqfv7QMWCW7Dk4/e8zNiCvavKd61wNWfT6ovpFL6EmGFGalbO2lciuE3luXeXaozVS69owoF+MneBpyNW/FjZGE2dan9HjDWR2kS2fUltBNA9ruAIFfW1jGKlJ9wFkepWjPqtV8o4ZS8TS4h77SlCzF8jpkrZ5UpoQxGRtG3IDUBWnM2mhg6aH55o8hYWHWZt/UjWJrZYBDpfuw/POX4FanMhjW2RyDvM9gLzORCb1ASg2l1ulToN7/LAnLBqLh0uZ9ktCSQHEw9N/g=
  skip_cleanup: true
  on:
    repo: lampix-org/lampixjs-physics
    all_branches: true
branches:
  only:
  - "/^release\\/\\d+\\.\\d+\\.\\d+$/"
